name: CZArcade Sheets JSON Retriever

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  convert-xlsx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl requests beautifulsoup4
        
      - name: Run JSON Making Script
        run: |
          python jsonMaker.py

      - name: Move JSON file
        run: |
          mv CZARCADE.json data/CZARCADE.json

      - name: Commit new JSON
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data/CZARCADE.json

          if ! git diff --cached --quiet; then
            git commit -m "Update CZARCADE.json"
            git push
          else
            echo "No changes to commit."
          fi